#!/usr/bin/env python3
"""
Generate Taxonomy Distribution Report

This script analyzes the distribution of concepts across taxonomy categories
and generates a markdown report.
"""

import csv
import sys
from collections import Counter


TAXONOMY_NAMES = {
    "FOUND": "Foundation Concepts",
    "GTECH": "Graph Technologies",
    "HCARE": "Healthcare Domain",
    "PAT": "Patient Data",
    "PROV": "Provider Operations",
    "PAYER": "Payer & Insurance",
    "FIN": "Financial & Business",
    "FRAUD": "Fraud & Compliance",
    "ANAL": "Graph Analytics",
    "AI": "AI & Machine Learning",
    "SEC": "Security & Privacy",
    "GOV": "Data Governance",
    "CAP": "Capstone & Career",
    "MISC": "Miscellaneous"
}


def read_csv(filename):
    """Read the CSV file and return taxonomy data."""
    taxonomies = []
    with open(filename, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            taxonomies.append(row['TaxonomyID'])
    return taxonomies


def generate_distribution_report(csv_file, output_file):
    """Generate taxonomy distribution markdown report."""
    taxonomies = read_csv(csv_file)
    total_concepts = len(taxonomies)
    tax_counts = Counter(taxonomies)

    # Sort by count (descending)
    sorted_tax = sorted(tax_counts.items(), key=lambda x: x[1], reverse=True)

    # Generate markdown report
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Taxonomy Distribution Report\n\n")
        f.write("This report shows how the 200 concepts are distributed across taxonomy categories.\n\n")

        # Summary statistics
        f.write("## Summary Statistics\n\n")
        f.write(f"- Total Concepts: {total_concepts}\n")
        f.write(f"- Number of Categories: {len(tax_counts)}\n")
        f.write(f"- Average Concepts per Category: {total_concepts / len(tax_counts):.1f}\n")
        f.write(f"- Largest Category: {TAXONOMY_NAMES.get(sorted_tax[0][0], sorted_tax[0][0])} ({sorted_tax[0][1]} concepts, {sorted_tax[0][1]/total_concepts*100:.1f}%)\n")
        f.write(f"- Smallest Category: {TAXONOMY_NAMES.get(sorted_tax[-1][0], sorted_tax[-1][0])} ({sorted_tax[-1][1]} concepts, {sorted_tax[-1][1]/total_concepts*100:.1f}%)\n\n")

        # Distribution table
        f.write("## Distribution by Category\n\n")
        f.write("| Rank | Taxonomy ID | Category Name | Count | Percentage | Visualization |\n")
        f.write("|------|-------------|---------------|-------|------------|---------------|\n")

        for rank, (tax_id, count) in enumerate(sorted_tax, 1):
            percentage = (count / total_concepts) * 100
            bar = '█' * int(percentage / 2)  # Simple bar chart (50% = 25 blocks)
            category_name = TAXONOMY_NAMES.get(tax_id, tax_id)
            f.write(f"| {rank} | {tax_id} | {category_name} | {count} | {percentage:.1f}% | {bar} |\n")

        f.write("\n")

        # Balance assessment
        f.write("## Balance Assessment\n\n")

        over_represented = [(tax, count) for tax, count in tax_counts.items() if count / total_concepts > 0.30]
        under_represented = [(tax, count) for tax, count in tax_counts.items() if count / total_concepts < 0.03]

        if not over_represented and not under_represented:
            f.write("✓ **Excellent**: The taxonomy distribution is well-balanced.\n\n")
        else:
            if over_represented:
                f.write("⚠ **Over-represented categories** (>30% of total):\n\n")
                for tax, count in over_represented:
                    f.write(f"- {TAXONOMY_NAMES.get(tax, tax)}: {count} concepts ({count/total_concepts*100:.1f}%)\n")
                f.write("\n")

            if under_represented:
                f.write("⚠ **Under-represented categories** (<3% of total):\n\n")
                for tax, count in under_represented:
                    f.write(f"- {TAXONOMY_NAMES.get(tax, tax)}: {count} concepts ({count/total_concepts*100:.1f}%)\n")
                f.write("\n")

        # Recommendations
        f.write("## Recommendations\n\n")

        if not over_represented and not under_represented:
            f.write("- No adjustments needed. The current distribution supports diverse learning pathways.\n")
        else:
            if over_represented:
                f.write("- Consider splitting over-represented categories into more specific subcategories.\n")
            if under_represented:
                f.write("- Consider merging under-represented categories with related topics or expanding content.\n")

        f.write("\n---\n\n")
        f.write("*Report generated by taxonomy-distribution.py*\n")

    print(f"Taxonomy distribution report written to {output_file}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python taxonomy-distribution.py <input-csv> <output-md>")
        sys.exit(1)

    csv_file = sys.argv[1]
    output_file = sys.argv[2]

    generate_distribution_report(csv_file, output_file)
